### ISSUE TITLE
Version compatibility

### ISSUE THREAD

**Issue by Rupa93** [kaarthiksundar/n-k#1]
Hi, 
I'm having trouble with the version compatibility as I try to run these scripts. The code seems to be written for PowerModels v0.3.0. 
I tried downgrading the PowerModels version to be able to run n-k related scripts. But when I do so, there seems to be an issue with JuMP pre-compilation. 
I was wondering if there is any quick fix to this issue. 
Thanks in advance!

**Comment by kaarthiksundar** [comment]
You are correct. There will be version compatibility issues. I have to make some updates to the code to make it run with the latest versions. Can you let me know which part of the codes you are trying to run so that I can update only those parts.

**Comment by Rupa93** [comment]
Thanks a lot for such a prompt response.
I'm trying to run main.jl in n-k\Deterministic.
This function calls prob.jl which uses the previous version of PowerModels data structure. This is where I get stuck.

**Comment by kaarthiksundar** [comment]
Great. I shall make the update over the weekend and let you know.

**Comment by kaarthiksundar** [comment]
In the Julia command prompt, execute the following command


````
Pkg.pin("PowerModels", v"0.3.0")
````

After running the code you want to run: execute

````
Pkg.free("PowerModels")
````

**Comment by Rupa93** [comment]
Hi, I still get this issue. It seems like downgrading PowerModels results in issues with JuMP package. The error is shown below:

ERROR: LoadError: LoadError: LoadError: invalid subtyping in definition of JuMPArray
Stacktrace:
 [1] include_from_node1(::String) at .\loading.jl:576
 [2] include(::String) at .\sysimg.jl:14
 [3] include_from_node1(::String) at .\loading.jl:576
 [4] include(::String) at .\sysimg.jl:14
 [5] include_from_node1(::String) at .\loading.jl:576
 [6] include(::String) at .\sysimg.jl:14
 [7] anonymous at .\<missing>:2
while loading C:\Users\Rupa\.julia\v0.6\JuMP\src\JuMPArray.jl, in expression starting on line 6
while loading C:\Users\Rupa\.julia\v0.6\JuMP\src\JuMPContainer.jl, in expression starting on line 11
while loading C:\Users\Rupa\.julia\v0.6\JuMP\src\JuMP.jl, in expression starting on line 55
ERROR: LoadError: Failed to precompile JuMP to C:\Users\Rupa\.julia\lib\v0.6\JuMP.ji.
Stacktrace:
 [1] compilecache(::String) at .\loading.jl:710
 [2] _require(::Symbol) at .\loading.jl:497
 [3] require(::Symbol) at .\loading.jl:405
 [4] include_from_node1(::String) at .\loading.jl:576
 [5] include(::String) at .\sysimg.jl:14
 [6] macro expansion at C:\Users\Rupa\.julia\v0.6\Atom\src\repl.jl:118 [inlined]
 [7] anonymous at .\<missing>:?
while loading C:\Users\Rupa\Documents\MyResearch\NETSSRelated\LANL\n-k\deterministic\main.jl, in exp
ression starting on line 1
